import * as THREE from "three";
import {OrbitControls} from "three/addons/controls/OrbitControls.js";

const CENTER={lon:113.9416,lat:22.5148},MX=111320*Math.cos(CENTER.lat*Math.PI/180),MZ=111320;
const springInfo={name:"中国华润大厦 · 春笋",height:392.5,levels:68};
const views={bird:{pos:[920,900,1260],look:[0,55,40]},lake:{pos:[-690,155,700],look:[0,140,-270]},tower:{pos:[250,265,150],look:[0,175,-325]},plan:{pos:[0,1900,8],look:[0,0,0]}};
const xy=([lon,lat])=>new THREE.Vector2((lon-CENTER.lon)*MX,-(lat-CENTER.lat)*MZ);
const num=v=>{const m=v?.match(/[\d.]+/);return m?Number(m[0]):0};
const center=p=>p.reduce((a,b)=>a.add(b),new THREE.Vector2()).divideScalar(p.length||1);
const area=p=>Math.abs(p.reduce((a,x,i)=>{const y=p[(i+1)%p.length];return a+x.x*y.y-y.x*x.y},0)/2);
const shape=p=>{const s=new THREE.Shape();p.forEach((x,i)=>i?s.lineTo(x.x,-x.y):s.moveTo(x.x,-x.y));s.closePath();return s};
const height=(e,a)=>num(e.tags.height)||num(e.tags.levels)*3.8||(a>9000?17+Math.abs(Math.sin(e.id*.00173))*18:a>2500?28+Math.abs(Math.sin(e.id*.00173))*48:12+Math.abs(Math.sin(e.id*.00173))*70);

async function loadMap(){
  const parts=Array.from({length:8},(_,i)=>`./data/map-${String(i).padStart(2,"0")}.bin`);
  const arrays=await Promise.all(parts.map(async url=>new Uint8Array(await(await fetch(url)).arrayBuffer())));
  const total=arrays.reduce((n,a)=>n+a.length,0),joined=new Uint8Array(total);let offset=0;arrays.forEach(a=>{joined.set(a,offset);offset+=a.length});
  const stream=new Blob([joined]).stream().pipeThrough(new DecompressionStream("gzip"));
  return JSON.parse(await new Response(stream).text());
}

const scene=new THREE.Scene();scene.background=new THREE.Color(0xe6e9e4);scene.fog=new THREE.FogExp2(0xe6e9e4,.00025);
const host=document.querySelector("#canvas"),camera=new THREE.PerspectiveCamera(37,innerWidth/innerHeight,1,6500);camera.position.set(...views.bird.pos);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;host.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.07;controls.screenSpacePanning=true;controls.minDistance=80;controls.maxDistance=3300;controls.maxPolarAngle=Math.PI/2.03;controls.target.set(...views.bird.look);
scene.add(new THREE.HemisphereLight(0xf9fcf7,0xaeb7ae,2.7));const sun=new THREE.DirectionalLight(0xfff5dc,3.6);sun.position.set(-620,1100,740);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-1200,right:1200,top:1200,bottom:-1200,near:80,far:2400});scene.add(sun);
const groups={buildings:new THREE.Group(),landscape:new THREE.Group(),water:new THREE.Group(),roads:new THREE.Group()};Object.values(groups).forEach(g=>scene.add(g));
const ground=new THREE.Mesh(new THREE.PlaneGeometry(2800,2800),new THREE.MeshStandardMaterial({color:0xe3e2dc,roughness:.98}));ground.rotation.x=-Math.PI/2;ground.position.y=-.35;ground.receiveShadow=true;scene.add(ground);const grid=new THREE.GridHelper(2800,56,0xc8ccc7,0xd5d8d3);grid.position.y=-.14;grid.material.opacity=.22;grid.material.transparent=true;scene.add(grid);
const normal=new THREE.MeshStandardMaterial({color:0xf0f0eb,roughness:.88}),named=new THREE.MeshStandardMaterial({color:0xf9f9f4,roughness:.72}),edge=new THREE.LineBasicMaterial({color:0xb5bbb6,transparent:true,opacity:.66}),water=new THREE.MeshStandardMaterial({color:0xaec7c2,roughness:.5,transparent:true,opacity:.84}),park=new THREE.MeshStandardMaterial({color:0xd8ded1,roughness:1});
let spring=new THREE.Vector3(0,0,-330),go=null,look=null,night=false;const targets=[];

function polygon(e,mat,y){const p=e.geometry.map(xy);if(p.length<3)return;const g=new THREE.ShapeGeometry(shape(p));g.rotateX(-Math.PI/2);const m=new THREE.Mesh(g,mat);m.position.y=y;m.receiveShadow=true;return m}
function lines(elements,types){const p=[];elements.forEach(e=>{if(!types.has(e.tags.highway))return;for(let i=1;i<e.geometry.length;i++){const a=xy(e.geometry[i-1]),b=xy(e.geometry[i]);p.push(a.x,.74,a.y,b.x,.74,b.y)}});const g=new THREE.BufferGeometry();g.setAttribute("position",new THREE.Float32BufferAttribute(p,3));return g}
function bamboo(pos){const g=new THREE.Group();g.position.set(pos.x,1,pos.y);const white=new THREE.MeshPhysicalMaterial({color:0xf9f9f3,roughness:.45,metalness:.07,clearcoat:.15}),base=new THREE.MeshStandardMaterial({color:0xe7e6df,roughness:.84});const podium=new THREE.Mesh(new THREE.CylinderGeometry(84,96,11,36),base);podium.position.y=5.5;podium.scale.z=.7;podium.userData.info=springInfo;g.add(podium);const profile=[[29,0],[31,22],[33,72],[34,142],[32,220],[28,285],[22,332],[13,366],[5.5,386],[.7,392.5]].map(([r,y])=>new THREE.Vector2(r,y));const tower=new THREE.Mesh(new THREE.LatheGeometry(profile,56),white);tower.position.y=17;tower.castShadow=true;tower.userData.info=springInfo;g.add(tower);const ribs=[];for(let i=0;i<28;i++){const t=i/28*Math.PI*2;for(let j=0;j<profile.length-1;j++){const a=profile[j],b=profile[j+1];ribs.push(Math.cos(t)*(a.x+.25),a.y+17,Math.sin(t)*(a.x+.25),Math.cos(t)*(b.x+.25),b.y+17,Math.sin(t)*(b.x+.25))}}const rg=new THREE.BufferGeometry();rg.setAttribute("position",new THREE.Float32BufferAttribute(ribs,3));g.add(new THREE.LineSegments(rg,new THREE.LineBasicMaterial({color:0xa7afa9,transparent:true,opacity:.72})));g.traverse(o=>{if(o.userData.info)targets.push(o)});return g}

const data=await loadMap();const buildings=data.elements.filter(e=>e.tags.building&&e.geometry.length>2),waters=data.elements.filter(e=>e.tags.natural==="water"),parks=data.elements.filter(e=>e.tags.leisure==="park");waters.forEach(e=>{const m=polygon(e,water,.24);if(m)groups.water.add(m)});parks.forEach(e=>{const m=polygon(e,park,.32);if(m)groups.landscape.add(m)});const bay=new THREE.Mesh(new THREE.PlaneGeometry(2800,780),water);bay.rotation.x=-Math.PI/2;bay.position.set(0,.18,1350);groups.water.add(bay);
const roadEls=data.elements.filter(e=>e.tags.highway);groups.roads.add(new THREE.LineSegments(lines(roadEls,new Set(["motorway","trunk","primary","secondary","tertiary","unclassified","residential"])),new THREE.LineBasicMaterial({color:0xaeb4b0,transparent:true,opacity:.86})),new THREE.LineSegments(lines(roadEls,new Set(["service","pedestrian","footway","path","cycleway","steps"])),new THREE.LineBasicMaterial({color:0xb9bdb8,transparent:true,opacity:.48})));
let n=0,springPos=new THREE.Vector2(0,-330);for(const e of buildings){const p=e.geometry.map(xy),c=center(p);if(e.tags.name?.includes("中国华润大厦")){springPos=c;continue}const a=area(p);if(a<20||a>85000)continue;const h=Math.min(height(e,a),260),info={name:e.tags.name||`后海建筑 ${String(e.id).slice(-4)}`,height:Math.round(h*10)/10,levels:num(e.tags.levels)||Math.round(h/3.8)};const geo=new THREE.ExtrudeGeometry(shape(p),{depth:h,bevelEnabled:false});geo.rotateX(-Math.PI/2);const mesh=new THREE.Mesh(geo,e.tags.name?named:normal);mesh.castShadow=h>45;mesh.receiveShadow=true;mesh.userData.info=info;groups.buildings.add(mesh);targets.push(mesh);if(h>110||e.tags.name)groups.buildings.add(new THREE.LineSegments(new THREE.EdgesGeometry(geo,28),edge));n++}groups.buildings.add(bamboo(springPos));spring.set(springPos.x,0,springPos.y);document.querySelector("#count").textContent=n+1;document.querySelector("#loading").classList.add("hide");

const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),tip=document.querySelector("#tip");function hit(ev){const r=renderer.domElement.getBoundingClientRect();pointer.set((ev.clientX-r.left)/r.width*2-1,-((ev.clientY-r.top)/r.height*2-1));ray.setFromCamera(pointer,camera);return ray.intersectObjects(targets,false)[0]}
renderer.domElement.addEventListener("pointermove",ev=>{const h=hit(ev);renderer.domElement.style.cursor=h?"pointer":"grab";if(h?.object.userData.info){const i=h.object.userData.info;tip.textContent=`${i.name} · ${i.height}m`;tip.style.left=ev.clientX+"px";tip.style.top=ev.clientY+"px";tip.classList.add("show")}else tip.classList.remove("show")});renderer.domElement.addEventListener("click",ev=>{const i=hit(ev)?.object.userData.info;if(!i)return;document.querySelector("#name").textContent=i.name;document.querySelector("#height").textContent=i.height+" m";document.querySelector("#levels").textContent=i.levels+" 层"});
document.querySelectorAll("[data-layer]").forEach(b=>b.addEventListener("click",()=>{b.classList.toggle("on");groups[b.dataset.layer].visible=b.classList.contains("on")}));document.querySelectorAll("[data-view]").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll("[data-view]").forEach(x=>x.classList.remove("on"));b.classList.add("on");const v=views[b.dataset.view];go=new THREE.Vector3(...v.pos);look=new THREE.Vector3(...v.look);if(b.dataset.view==="tower"){go.set(spring.x+250,265,spring.z+475);look.set(spring.x,175,spring.z)}controls.enabled=false}));
document.querySelector("#light").addEventListener("click",()=>{night=!night;const c=night?0x172721:0xe6e9e4;scene.background=new THREE.Color(c);scene.fog.color.setHex(c);sun.color.setHex(night?0x9fc5cd:0xfff5dc);sun.intensity=night?2.3:3.6});document.querySelector("#full").addEventListener("click",()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen());
function label(el,p){const q=p.clone().project(camera);el.style.display=q.z>1?"none":"flex";el.style.left=(q.x*.5+.5)*innerWidth+"px";el.style.top=(-q.y*.5+.5)*innerHeight+"px"}function animate(){requestAnimationFrame(animate);if(go&&look){camera.position.lerp(go,.055);controls.target.lerp(look,.055);if(camera.position.distanceTo(go)<2){go=null;look=null;controls.enabled=true}}controls.update();label(document.querySelector("#spring-label"),new THREE.Vector3(spring.x,430,spring.z));label(document.querySelector("#park-label"),new THREE.Vector3(-170,20,360));renderer.render(scene,camera)}animate();addEventListener("resize",()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
